/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Vinicius' at '18/05/16 00:21' with Gradle 2.13
 *
 * @author Vinicius, @date 18/05/16 00:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
